### ISSUE TITLE
Fire action when previous is done in queue

### ISSUE THREAD

**Issue by sanianman** [rgommezz/react-native-offline#148]
Hi, is it possible to fire action when previous action is done? Because next action depends on previous response from server.

**Comment by rgommezz** [comment]
I think your best shot would be to ignore the 2nd action, so that it doesn't go into the queue.

That way, once your 1st action is re-dispatched, the 2nd will follow as per your configuration in normal conditions.

Would that makes sense?

**Comment by sanianman** [comment]
No, it's impossible to do this way, I really need one after another action, I can't fire that action in previous.

**Comment by rgommezz** [comment]
What middleware are you using for async actions (server calls), thunks? Sagas?

> Because next action depends on previous response from server.

Could you show me your code where you set up that flow, so that I can have a better understanding of what's your intent?

**Comment by rgommezz** [comment]
I think I understand what you are trying to do, but that goes out of scope of the library. I recommend you StackOverflow as a better place for this sort of enquiries. Still, I'll try to help you.

You need to be crafty to orchestrate that logic. On top of my head, I would:
- Dispatch 1 thunk if I am offline, let's call it `createIfOffline`
- Dispatch a different thunk I am connected to the network, let's call it `createIfConnected`

Those two dispatches would occur from a redux _connected_ component, that is able to detect network transitions inside `componentDidUpdate` hook. `createIfConnected` is the thunk that encompasses all the normal server calls to create both project and client. `createIfOffline` though, would create temporary objects in the store with offline flags.

Your thunks could look like something like this (with dummy code and comments):

```js
const createIfOffline = (data) => {
    function thunk(dispatch, getState) {
        dispatch(createProject(data));
        // The temporary offlineId will be either created here,
        // or in the action creator (createProject) and stashed in the store.
        const offlineProjectId = getProjectIdSelector(getState());
        dispatch(createClient(offlineProjectId));
    }
    return thunk;
};

const createIfConnected = (data) => {
    async function thunk(dispatch) {
        const project = await createProject(data);
        dispatch(createProject(project));
        const client = await createClient(project.id);
        dispatch(createClient(project.id, client));
    }
    return thunk;
};
```

Now, I'd keep track on my store of projects created while offline, so that the next time I get back online I can check if there are some pending projects/clients to be sync up with the server and, if so, do it with a 3rd thunk.
