### ISSUE TITLE
How do you compare to redux-offline ?

### ISSUE THREAD

**Issue by AlbertoLopSie** [rgommezz/react-native-offline#167]
Hi man!

I'm sorry for posting this as an issue.

Could you elaborate about the differencies between this library and redux-offline?

I'm about to add offline capabilities to my Expo/RN app and wonder which one is better.

Thanks!

**Comment by rgommezz** [comment]
Hey @AlbertoLopSie,

Sorry but I am not familiar with how `redux-offline` work. On top of my head, the only thing I could tell you is that if you are working on a hybrid app or using `react-native-web`, `redux-offline` could be a better fit because it supports web as well. If you are only focusing on RN and what this library offers suffices your needs, prolly this one could be better.
