### ISSUE TITLE
do retry actions ever expire, or must they be manually removed from the queue?

### ISSUE THREAD

**Issue by luketgriffith** [rgommezz/react-native-offline#173]
First off, thanks for making this library, it has really helped us! We currently retry a lot of our actions if there is an error of some kind. If there is an action that is encountering a server error of some kind, does it get retried indefinitely until it is removed (or has a successful request)? Basically we would like to retry errors a set number of times, or for a certain time period, and then stop retrying.

**Comment by rgommezz** [comment]
Hey @luketgriffith,

Thanks for the kind words!

The queued actions never expire, so you would have to manually remove an action from the queue. At the moment, that API is not publicly exposed. I am thinking we could temporarily export the action creators as well, so that you can fire a `removeActionFromQueue` action when you please. What do you think?

If you fancy, you could put up a PR together.

**Comment by luketgriffith** [comment]
I ended up making a fork with some tweaks that suit our specific use case. I can try to make another better suited for general use though. I might be confused - wouldn't exposing the removeActionFromQueue action creator have the same effect as using the dismiss key?

**Comment by rgommezz** [comment]
Glad you find your way!

If you refer to `dispatching` an action that matches the removal action type from the library, yes.

Closing for now.
