### ISSUE TITLE
When app killed and opened data gets persisted but doesn't get dispatched

### ISSUE THREAD

**Issue by malikhzr** [rgommezz/react-native-offline#175]
Hi @rgommezz. First thank you for the amazing library.
I have an app where I collect user input and fetch and send to backend ones all collected. When  i blacklist the network and kill the app before i get internet and then  open my app I can see persisted data in my store but it doesn't get dispatched. When I whitelist network my store gets cleared and I get redirected to login page where I need to relogin and answer again. Please tell me what I might be missing?

Thanks in advance

**Comment by rgommezz** [comment]
Hi @malikhzr,

Thanks for the kind words!

Unfortunately I can't help with the blacklisting/whitelisting thing, since that's part of `redux-persist` (I assume) and outside of the scope of this library.

Once you figure that out, if you are persisting the `network` state and close the app while offline, it may be the case that you don't check connectivity back again during initialisation, so the store will be rehydrated with `isConnected = false`.
 
You'd have 2 options here:
- Don't persist the `isConnected` bit.
- Even better, [check connectivity on startup](https://github.com/rgommezz/react-native-offline#how-to-orchestrate-redux-to-dispatch-connection_change-as-the-first-action-when-the-app-starts-up)

**Comment by malikhzr** [comment]
Thanks fore the tips @rgommezz. I will try them. My bad about blacklisting/whitelisting. I have mentioned it since I followed the example in react-native-offline FAQ example. Now it works fine when I loose internet connection and receive it before I kill the app. But ones I reopen my store doesn't dispatch actions performed while in offline mode. I think I don't set up redux-persist properly I will try your tips.
