### ISSUE TITLE
Thunks not serialised correctly when using redux-persist

### ISSUE THREAD

**Issue by malikoum94** [rgommezz/react-native-offline#35]
hello,

when i use this module with redux-persist, if i have a actionQueue when i kill app, on resume i have always an error because it restore the actionQueue with an Array of null value.
Anyone else have this error?

thanks

**Comment by rauliyohmc** [comment]
Are you using `redux-thunk` as middleware? If so, my guess is that `redux-persist` is not able to serialise it to disk since the `actionQueue` would store functions in the array

**Comment by ahmb84** [comment]
I have the same problem, I'm using redux-persist and the actionQueue is an array of null

**Comment by patilrevansidh** [comment]
@ahmb84 
does your actionQueue persist even after app kill? if so then how you dispatch them again and how you stored by stringifying action? can you guide with some code sample?

**Comment by rauliyohmc** [comment]
Hi @richardvclam,

I had in mind to implement something like that when finding some free time. However, I have the feeling I am missing something in that implementation.

You are persisting on disk the name of the function and the arguments.
My concerns is about re-hyrdration, look at my comments in the below snippet:

```js
if (action.function) {
   // The below statement returns the name of the function, so a string.
   const actionFunction = actions[action.function];
   // Here, you are invoking a string as a function...so it should throw an exception?
   actionQueue.push(actionFunction(...action.args));
} 
``` 

Maybe I am missing something?

The idea I had in mind is to serialize and persist the function body using `Function.toString()` (besides the argument) and then on re-hydration, regenerate it with the function constructor:

```js
new Function (arg1, arg2, ... argN, functionBody)
```

**Comment by richardvclam** [comment]
Hi @rauliyohmc,

I believe you're missing the object that is mapping actions to its string.

```javascript
import { fetchUser } from './actions.js';
import { fetchOtherUsers } from './otherActions.js';

// This is the missing piece!
// We have to map our actions to an object
const actions = {
  fetchUser,
  fetchOtherUsers,
};

const networkTransform = createTransform(
  ...
  if (action.function) {
    // The below statement returns the function
    // with the string from the actions object.
    const actionFunction = actions[action.function];
    // Here, we are invoking the function
    actionQueue.push(actionFunction(...action.args));
  }
  ...
);
```


**Sidebar thoughts:**
I have also thought about using `eval` when defining the `actionFunction` - though I have not tested whether this will work. By doing this we wouldn't have to explicitly map our actions with an object. I'm hoping it would look something like this.

```javascript
// Still need to import actions
import { fetchUser } from './actions.js';
import { fetchOtherUsers } from './otherActions.js';

const networkTransform = createTransform(
  ...
  if (action.function) {
    // The below statement returns the name of the function,
    // which we'll use 'eval' to call the imported action.
    const actionFunction = eval(action.function);

    actionQueue.push(actionFunction(...action.args));
  }
  ...
);
```

**Thoughts on your implementation:**
I really like your idea of serializing the function body itself. This would remove the extra need for importing actions like in my implementation. Because I don't know of any easy way to save arguments, I'd assume you still have to include them in the meta.

One thing I'm concerned about with both of our implementations is the performance impact of using `eval` or creating a function from a string (which I'm assuming is using eval underneath - correct me if wrong).

Would love to hear more thoughts on all of this. Thanks!

**Comment by joaopiopedreira** [comment]
Bumped into this issue tonight, applied @richardvclam fix and worked like a charm. The performance impact is minimal. BTW, IMHO, I think `redux-persist` transforms are the way to go here. Thank you :-)

**Comment by rgommezz** [comment]
Hey @richardvclam, would you like to document the workaround through a PR as a new entry on the FAQ section? I think it will be useful for everyone that come across this issue :)

You know, basically a port of your comment https://github.com/rgommezz/react-native-offline/issues/35#issuecomment-375802151 and https://github.com/rgommezz/react-native-offline/issues/35#issuecomment-376618925.

**Comment by richardvclam** [comment]
@rgommezz, I'd be honored to!

**Comment by rgommezz** [comment]
Closed with https://github.com/rgommezz/react-native-offline/commit/2acaf659b602bb77b36156c54e9e005fcd63aa84

**Comment by malikhzr** [comment]
Hi @richardvclam. I am facing same issue even I have used the tranforms above. Once I kill and open my app I can persisted data in my store but it doesn't get dispatched. That happens when I blacklist network reducer while whitelisting network takes me initial login page and cleans my whole store so data also dont get persisted. What am I missing ?

**Comment by GhizlaneA** [comment]
Hi, I am still facing the same issue. The action "@@network-connectivity/FETCH_OFFLINE_MODE" is dispatched with an empty payload object:

type: "@@network-connectivity/FETCH_OFFLINE_MODE"
payload: { }
meta: {
  retry: true
  name: "myActionName"
  args: [{…}, 0, 0, 0, …]
}

And the state has an array of null in the network's action queue:
network: {
    isConnected: false,
    actionQueue: [null]
}

I am using redux-persist and I followed the workaround documented [here](https://github.com/rgommezz/react-native-offline/commit/2acaf659b602bb77b36156c54e9e005fcd63aa84).

**Comment by malikhzr** [comment]
Hi @GhizlaneA does this happens when you close(kill) the app while being offline and relaunch app as online ?

**Comment by GhizlaneA** [comment]
> Hi @GhizlaneA does this happen when you close(kill) the app while being offline and relaunch app as online ?

Hello @malikhzr, thanks for asking. No it happens when I am using the app. I did not kill it meanwhile.

**Comment by malikhzr** [comment]
> > Hi @GhizlaneA does this happen when you close(kill) the app while being offline and relaunch app as online ?
> 
> Hello @malikhzr, thanks for asking. No it happens when I am using the app. I did not kill it meanwhile.

@GhizlaneA it works for me while app is launched. E.g. I have no internet I answer my questions offline and send them to action queue get redirected to home page then switch on internet  and my actions get dispatched.

**Comment by matinzd** [comment]
> Closed with [2acaf65](https://github.com/rgommezz/react-native-offline/commit/2acaf659b602bb77b36156c54e9e005fcd63aa84)

My actionQueue is empty when app launches :(

**Comment by helderburato** [comment]
I used the workaround, but when kills the app and came back I receive the following error:

![Screen Shot 2020-07-28 at 13 25 09](https://user-images.githubusercontent.com/862575/88693586-da760300-d0d5-11ea-840d-4857ee726482.png)

After that, the `network => actionQueue` return empty array like below:
![Screen Shot 2020-07-28 at 13 25 19](https://user-images.githubusercontent.com/862575/88693632-e82b8880-d0d5-11ea-84cd-7e6a4ed99c0f.png)

**Comment by SainagChunduru** [comment]
> Hi @GhizlaneA does this happen when you close(kill) the app while being offline and relaunch app as online ?

Facing the same issue. Could anyone help on this?

**Comment by ryan-moreno** [comment]
> Hi, I am still facing the same issue. The action "@@network-connectivity/FETCH_OFFLINE_MODE" is dispatched with an empty payload object:
> 
> type: "@@network-connectivity/FETCH_OFFLINE_MODE" payload: { } meta: { retry: true name: "myActionName" args: [{…}, 0, 0, 0, …] }
> 
> And the state has an array of null in the network's action queue: network: { isConnected: false, actionQueue: [null] }
> 
> I am using redux-persist and I followed the workaround documented [here](https://github.com/rgommezz/react-native-offline/commit/2acaf659b602bb77b36156c54e9e005fcd63aa84).

Has anyone found a solution to this? I'm running into the same issue. I have created the thunk as described in the docs and added the meta and interceptInOffline attributes. When I'm offline, the action ``@@network-connectivity/FETCH_OFFLINE_MODE'' is published, but there is nothing in the payload of the action (I would expect something to be in payload.prevThunk). This causes the actionQueue to be appended with ``null'' instead of the actual function. This seems unrelated to redux-persist since the payload isn't even being populated within the action ``@@network-connectivity/FETCH_OFFLINE_MODE''.

I've read through all of the issues related to thunks for this repo, and all of the ones that mention this issue were directed to this issue #35, but I'm not finding a solution here. Any direction would be appreciated.

**Comment by vlad-datacat** [comment]
Same here. Removing redux persist reducer and gate completely - has no effect on thunks not being handled by react-native-offline. actionQueue always stores one null object, subsequent actions overwrite it, payload is empty same as for other issues on this repo...
