### ISSUE TITLE
Add Effective connection to network reducer state

### ISSUE THREAD

**Issue by rgommezz** [rgommezz/react-native-offline#43]
https://facebook.github.io/react-native/docs/netinfo.html#effectiveconnectiontype-enum

The network reducer state will have the next shape:

```js
type NetworkState = {
  isConnected: boolean,
  connectionType: '2g' | '3g' | '4g' | 'unknown',
  actionQueue: Array<*>
}
```

That will allow the user to dynamically set different timeouts for API calls, depending on the connection quality.

**Comment by ma-pe** [comment]
Listening to `'connectionChange'` returns the `type` and the `effectiveType`. Not the `isConnected` flag.

Do you think that `isConnected` always corresponds to `!['none','unknown'].includes(type)`?
If so, a PR seems easy and I'd like to help with that.

**Comment by rauliyohmc** [comment]
HI @ma-pe,

There are two types of listeners you can set on `NetInfo`.

```js
// On this one the handler retrieves information about the connection, like type and effective type. Not used by the library at the moment
NetInfo.addEventListener( 'connectionChange', handler);

// On this one the handler just gets the boolean `isConnected`. Used by the library
NetInfo.isConnected.addEventListener( 'connectionChange', handler);
```

Hope that clarifies your question.

Changing the listener is not that trivial work, since there are multiple connection types and Android has special values to deal with (like bluetooth and wimax), so it's not entirely cross-platform. I agree that an internet connection can be established through different standards, but I am not sure how reliable is the detection with React Native and seeing values like `unknown` confirms the uncertainty it carries away. 

If people start seeing a value on differentiating connection types, we could consider a new major version, but I am still not convinced nor I have the time to work on that.

**Comment by ma-pe** [comment]
Thanks for your reply. I agree with you on that.

I am using your library in combination with redux-saga. Since my app requires a "fast connection", I guess I'd best start listening on `CONNECTION_CHANGE` in a saga. There i can do the async call for the `type` and the `effectiveType` and dispatch it back. No need to alter your library for that.

I will let you know about my experiences with the relevance of `type` and `effectiveType`.

**Comment by vincenzovitale** [comment]
Having that in the store would allow to differentiate between data switched off and data connectivity lost, thus allowing to better inform the users with more meaningful messages.
In the first case it could be something like "Turn on the Data Connection" and in the second case for example "Connection to ACME server lost".

**Comment by ma-pe** [comment]
I added this functionality on my own using `redux-saga`.

I created a saga that listens to the `react-native-offline`-events. I use these events to ask for the connection-type. Than I release another action that I can process in my reducer:

```
import { put, takeLatest } from 'redux-saga/effects';

import { NetInfo } from 'react-native';
import { offlineActionTypes } from 'react-native-offline';

const checkConnectionType = function* checkConnectionType(action) {
  try {
    const connectionInfo = yield NetInfo.getConnectionInfo();

    yield put({ type: 'CONNECTION_CHANGE_TYPE', connectionInfo });
  } catch (error) {
    yield put({ type: 'CONNECTION_CHANGE_TYPE_ERROR', error });
  }
};

const mySaga = function* mySaga() {
  yield takeLatest(offlineActionTypes.CONNECTION_CHANGE, checkConnectionType);
};

export default mySaga;
```
