### ISSUE TITLE
Update specific data in ActionQueue

### ISSUE THREAD

**Issue by repapa** [rgommezz/react-native-offline#89]
Hi @rgommezz,

How can I update a specific data in actionQueue?

**Comment by rgommezz** [comment]
Hello,

Unfortunately that option doesn't exist at the moment, since the actionQueue is immutable and with FIFO mechanism.

A workaround may be to use the `dismiss` property on the meta object and set it to contain the same action dispatched, that way you'll only enqueue the most recent one dispatched, without duplications. Something like:

```js
const actionExample = {
  type: 'ACTION_EXAMPLE',
  meta: {
    retry: true,
    dismiss: ['ACTION_EXAMPLE'],
  },
};
```

For further API reference: https://github.com/rgommezz/react-native-offline#offline-queue
